### ISSUE TITLE
How access Custom field from templates?

### ISSUE THREAD

**Issue by StayPirate** [skx/rss2email#102]
Let's consider the following item, from a rss [feed](https://security.stackexchange.com/feeds):
```
    <entry>
        <id>https://security.stackexchange.com/q/261874</id>
        <re:rank scheme="https://security.stackexchange.com">0</re:rank>
        <title type="text">I found this json text in a .srt file for a video [closed]</title>
            <category scheme="https://security.stackexchange.com/tags" term="json" />
            <category scheme="https://security.stackexchange.com/tags" term="video" />
        <author>
            <name>Sad Lemon</name>
            <uri>https://security.stackexchange.com/users/277946</uri>
        </author>
        <link rel="alternate" href="https://security.stackexchange.com/questions/261874/i-found-this-json-text-in-a-srt-file-for-a-video" />
        <published>2022-05-10T05:17:10Z</published>
        <updated>2022-05-10T08:18:44Z</updated>
        <summary type="html">
            &lt;p&gt;So i am not [...] &gt;&#xA;
        </summary>
    </entry>
```
I'd like to access the `re:rank` value (which in this case is `0`) from the template, as I want this information available within the email. The gofeed library [provides](https://github.com/mmcdole/gofeed/blob/68ee9054d97bf13a4ac38f802d2e9c1bcff2991d/feed.go#L35) a `Custom` field, which I guess could be used to access any DOM item which is not processed by default. According to this assumption I tried something like the following, without any success.
```
Rank: {{.RSSFeed.Custom.re}}
```
```
Rank: {{.RSSFeed.Custom.rank}}
```
```
Rank: {{.RSSFeed.Custom["re"]}}
```
```
Rank: {{.RSSFeed.Custom.re:rank}}
```

**_How can I access that value and have it reported within the email?_**

**Comment by skx** [comment]
Fun question.

So first of all I wrote the following example script to experiment with stuff:

```
package main

import (
	"fmt"

	"github.com/mmcdole/gofeed"
)

func main() {

	// Read the feed
	fp := gofeed.NewParser()
	feed, err := fp.ParseURL("https://security.stackexchange.com/feeds")
	if err != nil {
		fmt.Printf("error parsing feed:%s\n", err)
		return
	}

	// Show the title
	fmt.Println(feed.Title)

	// For each feed-item show the values
	for _,entry := range feed.Items {

		// Show the feed-item's title.
		fmt.Printf("\t%s\n", entry.Title)

		// Get the rank, if present
		if entry.Extensions["re"] != nil {
			if entry.Extensions["re"]["rank"] != nil {

				for _, item := range(entry.Extensions["re"]["rank"] ) {
					fmt.Printf("XXXX %s -> %s\n", item.Name, item.Value)
				}
			}
		}
	}

}
```

Once I did that I came up with the following code:

```
{{ range $index, $map := index .RSSItem.Extensions "re" "rank" }}X-Rank: {{  $map.Value }}{{ end }}
```

I tested it on your field.  I did not test it on other fields - it might break if there are missing `re`:`rank` fields, but .. I hope that provides a starting-point at least.

**Comment by StayPirate** [comment]
Amazing, thank you! Do you think a more general way will be implemented in rss2email? IMO rss2email advanced users might find such a functionality a good one.

**Comment by StayPirate** [comment]
I see you used `entry.Extensions["re"]`, may I ask why didn't you used `Item.Custom` or `Feed.Custom`?

**Comment by skx** [comment]
> I see you used entry.Extensions["re"], may I ask why didn't you used Item.Custom or Feed.Custom?

The sample program proved that `Item.Custom` did not have the appropriate data.  (Nor did `Feed.Custom`).

**Comment by skx** [comment]
I initially assumed, as you, that "non-standard" things would end in the Custom map.  But when I iterated over it .. I saw only a license-key.

I'm not familiar enough with the internals of the `go-feed` library to know what should go where - but trial and error resulted in the template-snippet I posted above.

I guess this isn't really an issue with my project, but the upstream library and questions there would be better suited.

I'm happy to expand the contents of the feed-structure in our program, but I'd need to see what extensions were useful, as it seems a bit silly to add an `Extensions` map if that's already available within the `FeedItem` value..

**Comment by StayPirate** [comment]
Is it fine with you if I file an issue in the gofeed repo and loop you there?
Moreover, I'd like to ask you if you use any IM platform where people (like me), can reach out to you? If that's the case, I could avoid to flood this repo's issue tab with my weird questions :).

**Comment by skx** [comment]
I don't object to that.  Though I guess I'd be curious what issue you'd file - maybe unifying the "Custom" "Extension" "Dublin Core" and "ITunesExt" fields in one place, making it easy to iterate over?

I guess it's ugly but right now there are the ability to inspect custom/extra fields of various types.  It's a bit ugly to use them in the templates without trial and error, but I guess that could be improved by documentation (on our side).

As for IM - no, never.  Sorry.

If I'm busy, distracted, or not in the mood I'll just ignore emails and that's easy.  Generally I pay attention to projects and hobbies, but if I'm busy with real life I'll just ignore things for hours, days, weeks, or more.

I'm never gonna put myself in the position where my phone might make beeps and interrupt me with slack, kik, whatsapp, or any other IM on somebody elses schedule though, not unless I'm getting paid for it.

Nothing I do is critical, and while I try to help I'm not gonna feel bad if I make people wait because I'm in the pub, in a sauna, or spending time with family/friends/similar.

**Comment by skx** [comment]
I guess the initial problem reported here was resolved; you got access to the field(s) you wanted.

If you did want to followup with a report against the feed library then that might yield useful fruit in the future, but I guess that's outside the scope of this project.

So I guess time to close this :)
