### ISSUE TITLE
Unicode Parsing error

### ISSUE THREAD

**Issue by duckunix** [skx/rss2email#11]
After one of the blogs I follow updated, I now keep getting this error:

error processing https://blog.ktz.me/rss/ - error parsing https://blog.ktz.me/rss/ contents: XML syntax error on line 72: illegal character code U+001B

Is this something that can be fixed in the client?

Thanks!

**Comment by skx** [comment]
I think not.  The best thing that I could do is catch any errors encountered when processing the feed, and continue to the next one.  (This was improved in #10 - before then if there was an error in a single feed all subsequent ones would be skipped, now we just ignore the one that receives errors and keep going.)

It looks like I'm not alone in seeing the error with that particular feed:

* https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fblog.ktz.me%2Frss%2F

My suggestion would be to  report it to the author, and hope that the entry can be updated/escaped appropriately.

I'll take a look to see if I can filter out specific errors, but I think the chances are low.

**Comment by skx** [comment]
OK I took a look at this more carefully to see if I could fix it, but not easily I don't think.

The general flow goes:

* Parse list of URLs.
* For each one
  * Download the remote contents.
  * Pass to the feed-decoder

I thought i could remove bogus characters after downloading, but before decoding.  Unfortunately the decoding step handles all the content issues - when I receive the feed it doesn't have bogus UTF-8 characters, its the result of the decoding which is broken.

There are some transformer options I can play with, for the feed-parsing library I'm looking at, but I'm not optimistic.  I'll have a look tomorrow/wednesday.

**Comment by skx** [comment]
> There are some transformer options I can play with, for the feed-parsing library I'm looking at, but I'm not optimistic. I'll have a look tomorrow/wednesday.

I'm going to have to close/tag this as "can't fix".  The error occurs within the feedparser, and I guess the bug should be reported there:

* https://github.com/mmcdole/gofeed

Though I suspect any bug-report would be met with "Please fix your broken feed" it might not hurt to attempt it.

**Comment by duckunix** [comment]
Okay...thanks for looking into it.  I put a wrapper script around it for now.  I did reach out to the blog author, and he has no clue on why it is happening.
