### ISSUE TITLE
Build and publish the r2e container image to ghcr.io via GH Actions

### ISSUE THREAD

**Issue by StayPirate** [skx/rss2email#115]
Would you mind adding a GH action to build and publish r2e container images at every new release?

I tested within a fork, it's been very simple as I only needed to add the **Publish Docker Container** action (by Github Actions) from the Actions tab. In turn, it has created and merged [this file](https://github.com/StayPirate/rss2email/blob/master/.github/workflows/docker-publish.yml) to the forked repo.

**Comment by skx** [comment]
Happy to look at that, though at the same time I'm kinda conscious that if I push a broken commit I might break people relying upon the "master"/unstable image.  

That almost makes me think if people want to live on the edge they should maybe do it themselves?

**Comment by StayPirate** [comment]
I guess the Action can be customized to publish the image only on release events.

**Comment by StayPirate** [comment]
Looking at some examples online it seems that you can specify when the action triggers to the `on` stanza. The [following configuration](https://github.com/StayPirate/rss2email/blob/0ec9da0dc61cce4beb962edaeedae62dd70ff0a9/.github/workflows/docker-publish.yml#L8C3-L10) is the one set by default from the action I mentioned above:

```
on:
  schedule:
    - cron: '33 17 * * *'
```

According to [this example](https://docs.github.com/en/actions/publishing-packages/publishing-docker-images) it seems that you need sth like:

```
on:
  release:
    types: [published]
```
