### ISSUE TITLE
The url at the beginning and end of html content is not a correct link.

### ISSUE THREAD

**Issue by DaleFarnsworth** [skx/rss2email#12]
The url that appears in the received email is not clickable.

The '=' in the <a href="article_url"> from the email template is removed by the quoted-printable decoding when the email is received.

**Comment by skx** [comment]
I've not noticed a problem with this, but I'm going to assume it depends on the client to a certain extent.

What do you think the solution should be?  (It's been a while since I touched MIME, and I'm not sure if I can escape it, or if I should be using a different encoding instead.)

**Comment by skx** [comment]
Naively I'd assume "=" -> "=3D" would be a suitable escape/transformation.

**Comment by DaleFarnsworth** [comment]
Yes, changing the "=" to "=3D" fixed the problem.  I made a pull request that was identical to your proposed fix.  I'm happy if you use your own commit instead of pulling mine.

**Comment by DaleFarnsworth** [comment]
I added the change to convert the link to quoted-printable, per your suggestion.  I added that change to the same commit.

I discovered rss2email last night.  I like it.  It's minimal and the source is very clean.
