### ISSUE TITLE
Bug: Avoid exposing smtp password by modiying the template

### ISSUE THREAD

**Issue by faan11** [skx/rss2email#126]
Hi, 

As the title suggest, the SMTP password can be sent by email using a tailored email template that uses the env template function and the SMTP email method.
https://github.com/skx/rss2email/blob/c50930a58a308b39ee2d11ef6f619f8328468387/processor/emailer/emailer.go#L76

I propose two possible solutions:
- Store the SMTP password in memory (a "global" variable) and unset the SMTP_PASS variable.
- Returns empty if the env template  function looks for SMTP_PASS environment variable.

What do you think?

**Comment by skx** [comment]
I'm struggling to see a problem here:

* A user sets the environmental variable(s).
   *  SMTP_USER, SMTP_HOST, SMTP_PASS, etc. 
* The code running as that user has access to the variable(s)

If the users' account were compromised, for example, then they would get the value of the variable via the docker environment, cronjob, shell-file, or similar.  Waiting until it was set then echoing it via a custom template seems needlessly complex and unlikely.

If you have a situation where _multiple_ users each share one deployment and _some_ users shouldn't be able to inspect the values then that's .. unusual .. but there would be so many problems with that situation I'd still regard it as not a problem.

Can you eloborate more on why you think this is an issue?

**Comment by faan11** [comment]
This can be an issue when a normal user can modify the template file (due to loose permission). The normal user can modify the template by including a link/image with the password. The receiver of the mail can open the email and send the password to an external service.

I agree with you that this might sounds a remote scenario. The idea was to avoid adding sensitive details (such as the password) in the e-mail.

Feel free to consider this change or close the issue if you think that this is a remote case.

**Comment by skx** [comment]
* A normal user can modify the template used for sending emails.
* That could then include/expose the secret/password used for sending email, yes.
* However that secret is only present because the same user who setup rss2email configured it.
 
i.e.  A user can export a value that they **already know**.  If they wanted to expose it they could email it to their friends, write it on a password, or share it in numerous other means.

I don't see a security issue here, and I don't see a bug either.
