### ISSUE TITLE
Container not found on hub.docker.com

### ISSUE THREAD

**Issue by mklemme1** [skx/rss2email#128]
Hallo

I tried to use the `docker-compose.yml` found here in the repo.
Apparently the container is not found: 
```
# docker compose up
[+] Running 1/1
 ✘ rss2email Error                                                         1.2s 
Error response from daemon: pull access denied for skx/rss2email, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
#
```

Can you advise if I need to use another name?
Thanks

**Comment by skx** [comment]
I'm not sure there was ever a package there!  Anyway you should find the containers stored on github.

Look at the project, and on the right-hand side you'll see "Releases" and "Packages".  That second link will take you here:

* https://github.com/skx/rss2email/pkgs/container/rss2email

And that should be a stable/sane location to pull from.
