### ISSUE TITLE
Support ETag / If-Not-Modified headers

### ISSUE THREAD

**Issue by skx** [skx/rss2email#131]
Since I feel called out by Rachel's recent blog-posts.

rss2email works in two ways:

* Fire and forget: invoked by cron at the users's schedule.
   * It will process all the feeds once, then terminate.
* Deamon: run constantly sleeping between fetches.
   * This is the ideal place to add the support.

We have the boltdb for storing state of entries, I guess we can use that for storing etags, or we can just store in RAM - one string per endpoint - that might be quicker I guess in-practice that's fine.  We'd make one "raw" request on first-poll, and after that we'd save memory.  That perhaps is the pragmatic way to go.

**Comment by StayPirate** [comment]
That would be a very nice enhancement, thanks! By looking at the python [HTTP ETag docs](https://pythonhosted.org/feedparser/http-etag.html), I see they suggest to also use `Cache-control: max-age=60` to ensure the cache is not too old:

> You can control the behaviour of HTTP caches between your application and the origin server by using the `extra_headers` parameter. For example, you may want to send `Cache-control: max-age=60` to make the caches revalidate against the origin server unless their cached copy is less than a minute old. Again, this should be used with consideration.

I'm not sure if that's sth you are interested in or how much rss2email can benefit from it, but I'm sharing it here just FYI.

**Comment by skx** [comment]
Good comment, thank you :)

It's been a while since I had to mess with cache-related headers - after setting up haproxy & varnish back in the day - but I figure most things support Etags these days and that might be a simpler way to start than worrying about age/times.  

I'll make a quick check to see if that will help, and if it does it can go in to be improved in the future.

I guess my naive expectation is that I'd simply skip processing if the content is unchanged:

* Fetch the remote feed once, the first time.
* Store the Etag
* The next time make the request with that value.
* If we get an "unchanged" response then just return and skip processing the feed.

So I'm deliberately not going to cache the feed-body and return it if the cached value is still in-place.   Working on the assumption that if the remote content is unchanged then the items contained within it have already been processed.

(I realize this means that changes to filter/exclude/include won't be relfected, but if this is only in the case of a "deamon" run then they will be detected after a restart and I can live with that.)

**Comment by StayPirate** [comment]
Understood 👍🏼 . According to your bullet points, you are not using the `Last-Modified` header. In the same link I shared above they say:

> Clients should support both ETag and Last-Modified headers, as some servers support one but not the other.

**Comment by skx** [comment]
Yeah I'd hoped to skip the Last-Modified and just use Etag - mostly on the basis that I polled the feeds I'm using and all of the remote hosts did send Etag values.

I guess I will need to support both then!
