### ISSUE TITLE
Need ability to specify a from address for emails

### ISSUE THREAD

**Issue by DaleFarnsworth** [skx/rss2email#15]
It would be a nice enhancement to be able to optionally specify a From: address for the emails being sent that is different than the To: address.

**Comment by DaleFarnsworth** [comment]
Pull request #14 resolves this issue.

**Comment by skx** [comment]
Good suggestion, and apart from the minor wording suggestion on the help-string the pull-request looks great too.

Thanks for your interest and contributions :)
