### ISSUE TITLE
The Link template variable is used both in plain text context and quoted printable context

### ISSUE THREAD

**Issue by DaleFarnsworth** [skx/rss2email#18]
The Link template variable is used both in the email header (plain text) and in the html section (quoted printable).
I can think of two ways to fix this.  The simple way (which I favor) is to introduce a new QPLink variable that contains the quoted printable version and use it in the html section.  The more complex way would be to have separate templates for the various email sections and convert to quoted printable, when required, after the each template is executed.

**Comment by skx** [comment]
The alternative would be to append/prepend inside the HTML - to sidestep the need to explicitly use quoted-printable at all.

Right now we have the template containing:

      <a href=...
      {{.HTML}}
      <a href=...

If that were moved:

                x.HTML, err = toQuotedPrintable(html.UnescapeString(htmlstr))
                if err != nil {
                        return err
                }

We could instead use:

                htmlstr = "<p><a href=..." + htmlstr + "<a href ...</p>"
                x.HTML, err = toQuotedPrintable(html.UnescapeString(htmlstr))
                if err != nil {
                        return err
                }

A little horrid, but also probably OK.

**Comment by DaleFarnsworth** [comment]
I may not understand, but I don't see how that addresses the problem.  The conversion to quoted-printable or not need to happen on the value of the Link variable, not the template.

**Comment by skx** [comment]
Perhaps we're talking about different things.  I assumed you were referring to this part of the template:

```
{{.Link}}
--4186c39e13b2140c88094b3933206336f2bb3948db7ecf064c7a7d7473f2
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<p><a href=3D"{{.Link}}">{{.Link}}</a></p>
{{.HTML}}
<p><a href=3D"{{.Link}}">{{.Link}}</a></p>
--4186c39e13b2140c88094b3933206336f2bb3948db7ecf064c7a7d7473f2--

--76a1282373c08a65dd49db1dea2c55111fda9a715c89720a844fabb7d497--
--21ee3da964c7bf70def62adb9ee1a061747003c026e363e47231258c48f1--
```

If those links, above and below the HTML section, and moved into the HTML string then they get quoted along with the HTML-content itself.

If you're just talking about the {{.Link}} section itself, in the text/plain part, then that's handled by the conversion in the email_send.go file already:

                x.Link, err = toQuotedPrintable(link)

(As a result of your pull-request)

**Comment by DaleFarnsworth** [comment]
I _am_ talking about the {{.Link}} itself.  The change you mentioned fixed it when it used in the html section of the email.  However, {{.Link}} is also used in the header section, where it must be in plain text.  I guess the simplest fix of all would be to remove the X-RSS-Link: header entirely.

**Comment by DaleFarnsworth** [comment]
Note that the same issue exists with {{.Subject}}.  See issue #19.

**Comment by skx** [comment]
Ahah.  Now I understand.  Sorry for being slow.

**Comment by skx** [comment]
Using two variables is annoying but probably the right solution.

**Comment by skx** [comment]
Have a solution; will commit shortly.
