### ISSUE TITLE
Hide the URL when showing the item link in the html section

### ISSUE THREAD

**Issue by DaleFarnsworth** [skx/rss2email#19]
In the html section of the email template, I'd like to see

    <p><a href="{{.Link}}">{{.Link}}</a></p>

replaced by

    <p><a href="{{.Link}}">{{.Subject}}</a></p>

So that the item title is displayed in the email, rather than its URL.

**Comment by skx** [comment]
I'd be OK with that.

**Comment by skx** [comment]
Pending.

**Comment by skx** [comment]
Closed in #20.
