### ISSUE TITLE
Duplicate-removal is broken.

### ISSUE THREAD

**Issue by skx** [skx/rss2email#37]
Testing the code in #36:

```
$ cat ~/.rss2email/feeds
http://floooh.github.io/feed.xml
http://floooh.github.io/feed.xml
http://floooh.github.io/feed.xml
```

Add that same URL:

```
$ ./rss2email add http://floooh.github.io/feed.xml
$ cat ~/.rss2email/feeds
http://floooh.github.io/feed.xml
http://floooh.github.io/feed.xml
http://floooh.github.io/feed.xml
```

That's bad.  Also adding feeds takes forever now, because of validation...

**Comment by DaleFarnsworth** [comment]
I can't reproduce your duplicate removal problem.  Also, while adding an invalid feed takes about 5 seconds* because of retries, adding a valid feed doesn't take long.

For me:
```
time rss2email add http://floooh.github.io/feed.xml

real    0m0.123s
user    0m0.085s
sys     0m0.014s
```

We could probably reduce the retry count to 3.

**Comment by DaleFarnsworth** [comment]
There is a test for duplicate removal that passes.

**Comment by DaleFarnsworth** [comment]
Ah, I see now.  Duplicate removal doesn't remove existing duplicates.  It only prevents duplicates from being added.  Do we really want to scan the full feed list for duplicates each time we add one?

**Comment by DaleFarnsworth** [comment]
I guess it wouldn't hurt.  If you like, I'll make a new pull-request to do that.

**Comment by DaleFarnsworth** [comment]
Or, I guess we could remove existing duplicates as part of the cron sub-command, because we want to remove existing duplicate feeds even if we aren't going to add a new feed.

**Comment by DaleFarnsworth** [comment]
I pushed pull request #38 to address this issue.
