### ISSUE TITLE
Will this project support Windows?

### ISSUE THREAD

**Issue by gonejack** [skx/rss2email#54]
Hi, author. your source code of this project is so clear and neat. 

The only problem comes up in my mind while browsing this project is code like below will not work under Windows though I am not a Windows user myself:

https://github.com/skx/rss2email/blob/master/withstate/feeditem.go#L75-L86

**Comment by skx** [comment]
I'm not a windows user myself either, if users report problems I will try to fix them.

The code you highlight _should_ be OK:

* Read `$HOME`, use it if set.
* If not use [os.user.Current()](https://golang.org/pkg/os/user/#Current) to get the current user.
    * If that succeeds use [user.Homedir](https://golang.org/pkg/os/user/#User) to get their home-directory.
    * Which is probably something like `C:/Users/Steve`.
