### ISSUE TITLE
Feature Request: Trottling

### ISSUE THREAD

**Issue by duckunix** [skx/rss2email#6]
Hello,
Thanks for the software.  It works well and keeps me up to date on my RSS feeds.

So, the SMTP service I use only allows me to send x number of emails per hour to reduce spam usage.  Normally, I am good with that, but sometimes, I find that either I have added a new feed and forgot to do the -send=false, or that a large number of my feeds got very active for some reason, so I would like an option to say 'Quit nicely after sending X emails'.

I do run mine ever 15 minutes, and I currently have 99 feeds listed.

Thanks!

**Comment by skx** [comment]
Thanks for the report!  I can't help thinking this is the wrong layer to solve the problem, I'd be half-inclined to say "Email user@localhost", and then have the local SMTP deamon receive the mail, forwarding it to the real destination, and obeying the rate-limiting behaviour there.

That said I could imagine adding either:

* A delay flag, to sleep 1-Nseconds between each email.
* A one-shot flag, to send at most one notification, then exit.

The downsides are probably obvious; if you have a small delay in the first case it might not be sufficient to handle your SMTP servers issue.  For the second case if you have a new feed with 50 emails, and you send one email per run that's 50 * 15minutes = 12 hours before you're caught up.  More if new feed-items appear in the meantime.

Would either of those two solutions seem useful to you?

**Comment by duckunix** [comment]
I had not thought about the first option.  I do run this on one of my servers, so that should be a doable solution for me.

My actual long-term solution is to move off a managed SMTP service, but that is another story.

Thanks!
