### ISSUE TITLE
Add support for GOINSECURE and/or GOPRIVATE for SMTP

### ISSUE THREAD

**Issue by woulf** [skx/rss2email#67]
Hello,
In the current implementation you cannot send email trough a smtp server using a self signed certificate.
it would be nice to be able to use the GOINSECURE or GOPRIVATE environnement variable for testing purpose in this case.

thanks

**Comment by skx** [comment]
I don't have such a setup to test against, but if you were to submit a pull-request I'd be happy to review it :)

**Comment by woulf** [comment]
Hello,
i honestly tried but my knowledge of go being zero it wasn't easy.
according to the commit it seems that those variable are only used for HTTP calls, as i'm seeing a web object, not for the smtp interface: https://github.com/golang/go/commit/42db1da8e9def3490ed904594ad80e1090bff654
so i guess i'll just close the issue, sorry for the inconvenience :D
