### ISSUE TITLE
Feature Request: add feed URL as an X-Header

### ISSUE THREAD

**Issue by duckunix** [skx/rss2email#7]
I have not looked at the code, so I am not sure how easy this would be, but if the feed file had a site called `https://www.example.com/blog/rss.xml`, could there also be an X-Header called `X-RSS-FEED: https://www.example.com/blog/rss.xml`?

This would help for filtering emails as most email filters have built-in support for X-Headers as a filter rule, and it is more expensive to look into the body of the email.

Thanks!

**Comment by skx** [comment]
That's an excellent suggestion, and one I'd be happy to implement.

I'll add `X-RSS-Feed` and `X-RSS-Link` to contain the feed, and the permalink to the specific entry.  Adding both at once is as much work as just the first, and it might be useful..

**Comment by skx** [comment]
Released:

* https://github.com/skx/rss2email/releases/tag/release-1.2

**Comment by duckunix** [comment]
Awesome!  Thank you very much!
