### ISSUE TITLE
If httpfetch fails all feed entries become unseen

### ISSUE THREAD

**Issue by visit1985** [skx/rss2email#80]
Hi,

first, thanks for this great tool, it makes live much easier!

I recently came across an issue, when fetching a feed which has some rate limiting applied.
When httpfetch fails with "Failed to detect feed type", rss2email seems to forget all seen feed entries for that feed.
Would it make sense to do the cleanup only if all fetches succeed?

Thanks,
Michael

**Comment by skx** [comment]
Yes that would make sense.  Thanks for the report, I'll try to take a look at it over the next couple of evenings.
