### ISSUE TITLE
Feature Request - Better error handling

### ISSUE THREAD

**Issue by duckunix** [skx/rss2email#9]
Currently, if there is an error with retrieving a URL for any reason (transient or fatal) rss2email will simple exit with an error message.  This will cause me some issues as it might take me a day or so to notice the lack of emails, and when I go fix the error (normally by pushing the offending URL to the bottom if it is transient) I get a flood of email.

My request is to have rss2email throw the error to stdout, but continue with its run, and then exit with an error code.  This way, I get the error from cron, but I still get my rss feeds.

Thanks!

**Comment by skx** [comment]
That's a good idea, will implement shortly.  Thanks for the bug-report/suggestion :)

**Comment by skx** [comment]
* Resolved in #10.
* Released in [release-1.3](https://github.com/skx/rss2email/releases/tag/release-1.3)

**Comment by duckunix** [comment]
Thanks for the awesome turn-around time. :)
